apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: nais-blog
  namespace: plattformsikkerhet
  labels:
    team: plattformsikkerhet
spec:
  image: {{ image }}
  port: 80
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  liveness:
    path: /internal/isalive
    port: 8080
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/isready
    port: 8080
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  tokenx:
    enabled: true

  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
